var pathSegment = {
    НОВОСТИ: "/news",
    СПОРТ: "/sport",
    ФИНАНСЫ: "/finance",
    ВИДЕО: "/video",
    НАСТРОЕНИЕ: "/mood",
    АВТО: "/auto",
    ВЕЛО: "/velo",
    ТЕХНО:"/techno",
    АРХИТЕКТУРА: "/architecture",
    "ШОУ-BIZ": "/showbiz",
    LIFESTYLE: "/lifestyle",
    "СЕМЬЯ И ДЕТИ": "family",
    Украина: "/ukraine",
    Мир: "/world",
    Столица: "/capital",
    Жизнь: "/life",
    Футбол: "/football",
    Бокс: "/boks",
    Баскетбол: "/basketball",
    Хоккей: "/hockey",
    Теннис: "/tennis",
    Экономика: "/economy",
    Бизнес: "/business",
    "Личный бюджет": "/personalbudget",
    Недвижимость: "/realty",
    "Карьера и образование": "/career",
    "Все категории": "/allcategories",
    Ржаки: "/humor",
    Музыка: "/music",
    Спорт: "/sport",
    Животные: "/animals",
    Автоновости: "/autonews",
    ДТП: "/dtp",
    Автосоветы: "/autoadvice",
    Автоприколы: "/autojokes",
    "Тест-драйвы": "/testdrive",
    "Технологии и открытия": "/technolgy",
    Космос: "/cosmos",
    "Полезные советы": "/usefultips",
    Игры: "/games"
  };

  export default pathSegment;